- name: Upgrade cloak-server
  pip: name=cloak-server virtualenv=/home/cloak/venv state=latest

- name: Download the PKI (will wait for certificate approval)
  command: /home/cloak/bin/cloak-server pki --out /home/cloak/pki --wait
  async: 300
  poll: 1

- name: Initialize CRLs
  shell: '/home/cloak/bin/cloak-server crls --infile /home/cloak/pki/crl_urls.txt --out /home/cloak/pki/crls --format pem --post-hook "cat /home/cloak/pki/crls/*.pem > /home/cloak/pki/crls.pem"'

- name: Diffie-Hellman parameters
  copy: dest=/home/cloak/pki/dh2048.pem src=dh2048.pem
